# 0. Exercises and Practice

## Array Manipulations -- From SciPy Lecture Notes

### 1. Form the 2-D array (without typing it in explicitly)::

        [[1,  6, 11],
         [2,  7, 12],
         [3,  8, 13],
         [4,  9, 14],
         [5, 10, 15]]

   and generate a new array containing its 2nd and 4th rows.

In [1]:
#Put your additional code to answer the exercise here!
import numpy as np
a = np.arange(1,6)
b = np.arange(6,11)
c = np.arange(11,16)
print(a,b,c)

[1 2 3 4 5] [ 6  7  8  9 10] [11 12 13 14 15]


In [3]:
myarray = np.column_stack([a,b,c])
print(myarray)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [4]:
mysubarray = myarray[(1,3),:]
print(mysubarray)

[[ 2  7 12]
 [ 4  9 14]]


In [46]:
a = np.arange(1,16).reshape(3,5)
print(a)
print(a.T)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


### 2. Divide each column of the array ``a`` elementwise with the array ``b``.

(Hint: ``np.newaxis``).

In [48]:
import numpy as np
a = np.arange(25).reshape(5, 5)
b = np.array([1., 5, 10, 15, 20])  #Here b is an ARRAY .. so we need to do different operations.
print(a)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[  1.   5.  10.  15.  20.]


In [49]:
#Put your additional code to answer the exercise here!
print(b[:,np.newaxis])
print(a/b[:,np.newaxis])
print("The next two commands don't work with b as an array/vector")
print(b.T)
print(a/np.swapaxes(b,0,1))

[[  1.]
 [  5.]
 [ 10.]
 [ 15.]
 [ 20.]]
[[ 0.          1.          2.          3.          4.        ]
 [ 1.          1.2         1.4         1.6         1.8       ]
 [ 1.          1.1         1.2         1.3         1.4       ]
 [ 1.          1.06666667  1.13333333  1.2         1.26666667]
 [ 1.          1.05        1.1         1.15        1.2       ]]
The next two commands don't work with b as an array/vector
[  1.   5.  10.  15.  20.]


ValueError: bad axis2 argument to swapaxes

In [50]:
b = np.array([[1., 5, 10, 15, 20]]) #If we make b an actual vector/matrix... then these work...
print(a)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[  1.   5.  10.  15.  20.]]


In [51]:
print(a/b.T)
print("---")
print(a/np.swapaxes(b,0,1))

[[ 0.          1.          2.          3.          4.        ]
 [ 1.          1.2         1.4         1.6         1.8       ]
 [ 1.          1.1         1.2         1.3         1.4       ]
 [ 1.          1.06666667  1.13333333  1.2         1.26666667]
 [ 1.          1.05        1.1         1.15        1.2       ]]
---
[[ 0.          1.          2.          3.          4.        ]
 [ 1.          1.2         1.4         1.6         1.8       ]
 [ 1.          1.1         1.2         1.3         1.4       ]
 [ 1.          1.06666667  1.13333333  1.2         1.26666667]
 [ 1.          1.05        1.1         1.15        1.2       ]]


### 3. Harder one: Generate a 10 x 3 array of random numbers (in range [0,1]).
   For each row, pick the number closest to 0.5.

   - Use ``abs`` and ``argsort`` to find the column ``j`` closest for
     each row.

   - Use fancy indexing to extract the numbers.  (Hint: ``a[i,j]`` --
     the array ``i`` must contain the row numbers corresponding to stuff in
     ``j``.)

In [62]:
#Put your additional code to answer the exercise here!
randarry = np.random.rand(10,3)
print(randarry)


[[ 0.40455147  0.79144583  0.93218615]
 [ 0.76366634  0.73488871  0.840182  ]
 [ 0.0443429   0.60701684  0.12597524]
 [ 0.33368313  0.25718737  0.20342042]
 [ 0.42226409  0.52349345  0.88037332]
 [ 0.15505445  0.73863724  0.32878009]
 [ 0.28801444  0.39194543  0.62579466]
 [ 0.30864849  0.91679441  0.83888483]
 [ 0.45974035  0.01046192  0.96936886]
 [ 0.02688044  0.16499487  0.83106187]]


In [65]:
#Find distance from 0.5
print("Distance from 0.5")
print(randarry-0.5)
print("Absolute distance from 0.5")
dist05=np.abs(randarry-0.5)
print(dist05)

Distance from 0.5
[[-0.09544853  0.29144583  0.43218615]
 [ 0.26366634  0.23488871  0.340182  ]
 [-0.4556571   0.10701684 -0.37402476]
 [-0.16631687 -0.24281263 -0.29657958]
 [-0.07773591  0.02349345  0.38037332]
 [-0.34494555  0.23863724 -0.17121991]
 [-0.21198556 -0.10805457  0.12579466]
 [-0.19135151  0.41679441  0.33888483]
 [-0.04025965 -0.48953808  0.46936886]
 [-0.47311956 -0.33500513  0.33106187]]
Absolute distance from 0.5
[[ 0.09544853  0.29144583  0.43218615]
 [ 0.26366634  0.23488871  0.340182  ]
 [ 0.4556571   0.10701684  0.37402476]
 [ 0.16631687  0.24281263  0.29657958]
 [ 0.07773591  0.02349345  0.38037332]
 [ 0.34494555  0.23863724  0.17121991]
 [ 0.21198556  0.10805457  0.12579466]
 [ 0.19135151  0.41679441  0.33888483]
 [ 0.04025965  0.48953808  0.46936886]
 [ 0.47311956  0.33500513  0.33106187]]


In [72]:
print(np.argsort(dist05,axis=1))
indx_to_closest = np.argsort(dist05,axis=1)[:,0]
print(indx_to_closest)

[[0 1 2]
 [1 0 2]
 [1 2 0]
 [0 1 2]
 [1 0 2]
 [2 1 0]
 [1 2 0]
 [0 2 1]
 [0 2 1]
 [2 1 0]]
[0 1 1 0 1 2 1 0 0 2]


In [76]:
print(randarry)
print(randarry[np.arange(10),indx_to_closest].T)

[[ 0.40455147  0.79144583  0.93218615]
 [ 0.76366634  0.73488871  0.840182  ]
 [ 0.0443429   0.60701684  0.12597524]
 [ 0.33368313  0.25718737  0.20342042]
 [ 0.42226409  0.52349345  0.88037332]
 [ 0.15505445  0.73863724  0.32878009]
 [ 0.28801444  0.39194543  0.62579466]
 [ 0.30864849  0.91679441  0.83888483]
 [ 0.45974035  0.01046192  0.96936886]
 [ 0.02688044  0.16499487  0.83106187]]


AttributeError: 'list' object has no attribute 'T'

## Some Basic Image Transformations

Our goal in this set of code/exercises is to:
* Create a simple grid of points in 2-D Space
* Applied a graduated color scheme to those points
* Plot the points
* Perform some basic linear transformations on the points (and observe their movements)
* (Advanced) -- Animate the transitions between the points.

The cells below contains quite a bit of ``helper`` code to get going on some of the more difficult portions of these tasks (coloring, animation). If you are feeling adventuresome or confidence, try just adding a cell below THIS... and doing it all yourself! If not, use the portions below to get you jump-started.



In [ ]:
##Blank Cell for the Adventuresome!






### Generating and Plotting the basic, colored points

In [ ]:
# Visualizing 2D linear transformations as animated gifs
#
# Code originally created by: Raibatak Das
# Date: Nov 2016, Final version Dec. 2016
#
# Modified by: Karl Schmitt
# Modifications REMOVED significant portions for teaching purposes
# Last Modified 8/23/18

## PART 1

import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

# Create a grid of points in x-y space 

        # Hint: Use mgrid, but in 2-D space....
xygrid = #???
    
    
# Plot original grid points
# This function assigns a unique color based on position
def colorizer(x, y):
    """
    Map x-y coordinates to a rgb color
    """
    r = min(1, 1-y/3)
    g = min(1, 1+y/3)
    b = 1/4 + x/16
    return (r, g, b)

# Map grid coordinates to colors
colors = list(map(colorizer, xygrid[0], xygrid[1]))

# Plot x-y grid points 
plt.figure(figsize=(4, 4), facecolor="w")
plt.scatter(xygrid[0], xygrid[1], c=colors, edgecolor="none")
# Set axis limits
plt.grid(True)
plt.axis("equal")
plt.title("Original grid in x-y space")

# uncomment to save plot
#plt.savefig("../figures/grid-original.png", dpi=150)
#plt.savefig("../figures/grid-original-small.png", dpi=75)

### Now we'll try some transformations and plot the changed points.

In [ ]:
# Visualizing 2D linear transformations as animated gifs
#
# Code originally created by: Raibatak Das
# Date: Nov 2016, Final version Dec. 2016
#
# Modified by: Karl Schmitt
# Modifications REMOVED significant portions for teaching purposes
# Last Modified 8/23/18

## PART 2

# Transform and plot the grid points

In the cell below, apply a linear transformation using the matrix:

        [[2,  1],
         [-1,  1]]

Store that new matrix as ``uvgrid``

Hint: To do matrix multiplication, use: ``np.dot( <left matrix>, <right matrix> )``

In [ ]:
# Apply linear transform
a = #Define your transformation matrix here
print(a)
uvgrid = # Put your multiplication of a and xygrid here

In [ ]:
def plot_transform(uvgrid, colors):
    # Plot transformed grid points
    plt.figure(figsize=(4, 4), facecolor="w")
    plt.scatter(uvgrid[0], uvgrid[1], c=colors, edgecolor="none")
    plt.grid(True)
    plt.axis("equal")
    plt.title("Transformed grid in u-v space")
    # uncomment to save plot
    #plt.savefig("../figures/grid-transformed.png", dpi=150)
    #plt.savefig("../figures/grid-transformed-small.png", dpi=75)
    
plot_transform(uvgrid, colors)

Let's animate this transformation!

In [ ]:
# To animate the transform, we generate a series of intermediates
# Function to compute all intermediate transforms
def stepwise_transform(a, points, nsteps=30):
    '''
    Generate a series of intermediate transform for the matrix multiplication
      np.dot(a, points) # matrix multiplication
    starting with the identity matrix, where
      a: 2-by-2 matrix
      points: 2-by-n array of coordinates in x-y space 
    returns a (nsteps + 1)x2xn array
    '''
    # create empty array of the right size
    transgrid = np.zeros((nsteps+1,) + np.shape(points))
    for j in range(nsteps+1):
        intermediate = np.eye(2) + j/nsteps*(a - np.eye(2)) # compute intermediate matrix
        transgrid[j] = np.dot(intermediate, points) # apply intermediate matrix transformation
    return transgrid

# Apply to x-y grid
steps = 30
transform = stepwise_transform(a, xygrid, nsteps=steps)

# Create a series of figures showing the intermediate transforms
def make_plots(transarray, color, outdir="png-frames", figuresize=(4,4), figuredpi=150):
    '''
    Generate a series of png images showing a linear transformation stepwise
    '''
    nsteps = transarray.shape[0]
    ndigits = len(str(nsteps)) # to determine filename padding
    maxval = np.abs(transarray.max()) # to set axis limits
    # create directory if necessary
    import os
    if not os.path.exists(outdir):
        os.makedirs(outdir)
    # create figure
    plt.ioff()
    fig = plt.figure(figsize=figuresize, facecolor="w")
    for j in range(nsteps): # plot individual frames
        plt.cla()
        plt.scatter(transarray[j,0], transarray[j,1], s=36, c=color, edgecolor="none")
        plt.xlim(1.1*np.array([-maxval, maxval]))
        plt.ylim(1.1*np.array([-maxval, maxval]))
        plt.grid(True)
        plt.draw()
        # save as png
        outfile = os.path.join(outdir, "frame-" + str(j+1).zfill(ndigits) + ".png")
        fig.savefig(outfile, dpi=figuredpi)
    plt.ion()

# Generate figures
make_plots(transform, colors, outdir="tmp")

The following code for making a gif may not work on every system...

In [ ]:
# Convert to gif (works on linux/os-x, requires image-magick)
from subprocess import call
call("cd png-frames && convert -delay 10 frame-*.png ../animation.gif", shell=True)
# Optional: clean up png files
call("rm -f png-frames/*.png", shell=True)

Alright, time for some more challenging transformations...

Here I'll just specify what the transformation.. you'll need to determine what the matrix looks like!

In [ ]:
# Example 2: Rotation
# 60 degree clockwise rotation  -- Hint, you'll need sin and cos...
a = 
print(a)
uvgrid = # generate!
plot_transform(uvgrid, colors)

#Make animations
# Generate intermediates
transform = stepwise_transform(a, xygrid, nsteps=steps)
make_plots(transform, colors)
# see above to create gif

# Example 3: Shear
a =  # shear along x-axis
print(a)
uvgrid = # generate!
plot_transform(uvgrid, colors)

#Make animations
# Generate intermediates
transform = stepwise_transform(a, xygrid, nsteps=steps)
make_plots(transform, colors)
# see above to create gif

# Example 4: Permutation
a = 
print(a)
uvgrid = # generate!
plot_transform(uvgrid, colors)

#Make animations
# Generate intermediates
transform = stepwise_transform(a, xygrid, nsteps=steps)
make_plots(transform, colors)
# see above to create gif

# Example 5: Projection
a = 
print(a)
uvgrid = # generate!
plot_transform(uvgrid, colors)

#Make animations
# Generate intermediates
transform = stepwise_transform(a, xygrid, nsteps=steps)
make_plots(transform, colors)
# see above to create gif

## Picture manipulation: Framing a Face
------------------------------------

Let's do some manipulations on numpy arrays by starting with an image
of a racoon.  ``scipy`` provides a 2D array of this image with the
``scipy.misc.face`` function::

In [ ]:
from scipy import misc
face = misc.face(gray=True)  # 2D grayscale image

Here are a few images we will be able to obtain with our manipulations:
use different colormaps, crop the image, change some parts of the image.

* Create an array of the image with a narrower centering : for example,
    remove 100 pixels from all the borders of the image. To check the result,
    display this new array with ``imshow``.

* We will now frame the face with a black locket. For this, we
    need to create a mask corresponding to the pixels we want to be
    black. The center of the face is around (660, 330), so we defined
    the mask by this condition ``(y-300)**2 + (x-660)**2``

    Change the circle to an ellipsoid.
