# 0. Exercises and Practice

## Array Manipulations -- From SciPy Lecture Notes

### 1. Form the 2-D array (without typing it in explicitly)::

        [[1,  6, 11],
         [2,  7, 12],
         [3,  8, 13],
         [4,  9, 14],
         [5, 10, 15]]

   and generate a new array containing its 2nd and 4th rows.

In [2]:
#Put your additional code to answer the exercise here!
import numpy as np
a = np.arange(1,6)
b = np.arange(6,11)
c = np.arange(11,16)
print(a,b,c)

[1 2 3 4 5] [ 6  7  8  9 10] [11 12 13 14 15]


In [3]:
myarray = np.column_stack([a,b,c])
print(myarray)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [4]:
mysubarray = myarray[(1,3),:]
print(mysubarray)

[[ 2  7 12]
 [ 4  9 14]]


In [5]:
a = np.arange(1,16).reshape(3,5)
print(a)
print(a.T)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


### 2. Divide each column of the array ``a`` elementwise with the array ``b``.

(Hint: ``np.newaxis``).

In [6]:
import numpy as np
a = np.arange(25).reshape(5, 5)
b = np.array([1., 5, 10, 15, 20])  #Here b is an ARRAY .. so we need to do different operations.
print(a)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[  1.   5.  10.  15.  20.]


In [7]:
#Put your additional code to answer the exercise here!
print(b[:,np.newaxis])
print(a/b[:,np.newaxis])
print("The next two commands don't work with b as an array/vector")
print(b.T)
print(a/np.swapaxes(b,0,1))

[[  1.]
 [  5.]
 [ 10.]
 [ 15.]
 [ 20.]]
[[ 0.          1.          2.          3.          4.        ]
 [ 1.          1.2         1.4         1.6         1.8       ]
 [ 1.          1.1         1.2         1.3         1.4       ]
 [ 1.          1.06666667  1.13333333  1.2         1.26666667]
 [ 1.          1.05        1.1         1.15        1.2       ]]
The next two commands don't work with b as an array/vector
[  1.   5.  10.  15.  20.]


ValueError: bad axis2 argument to swapaxes

In [9]:
b = np.array([[1., 5, 10, 15, 20]]) #If we make b an actual vector/matrix... then these work...
print(a)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[  1.   5.  10.  15.  20.]]


In [10]:
print(a/b.T)
print("---")
print(a/np.swapaxes(b,0,1))

[[ 0.          1.          2.          3.          4.        ]
 [ 1.          1.2         1.4         1.6         1.8       ]
 [ 1.          1.1         1.2         1.3         1.4       ]
 [ 1.          1.06666667  1.13333333  1.2         1.26666667]
 [ 1.          1.05        1.1         1.15        1.2       ]]
---
[[ 0.          1.          2.          3.          4.        ]
 [ 1.          1.2         1.4         1.6         1.8       ]
 [ 1.          1.1         1.2         1.3         1.4       ]
 [ 1.          1.06666667  1.13333333  1.2         1.26666667]
 [ 1.          1.05        1.1         1.15        1.2       ]]


### 3. Harder one: Generate a 10 x 3 array of random numbers (in range [0,1]).
   For each row, pick the number closest to 0.5.

   - Use ``abs`` and ``argsort`` to find the column ``j`` closest for
     each row.

   - Use fancy indexing to extract the numbers.  (Hint: ``a[i,j]`` --
     the array ``i`` must contain the row numbers corresponding to stuff in
     ``j``.)

In [11]:
#Put your additional code to answer the exercise here!
randarry = np.random.rand(10,3)
print(randarry)


[[ 0.82203111  0.71669347  0.89493504]
 [ 0.98745974  0.91556332  0.63140939]
 [ 0.69521917  0.08948081  0.69250661]
 [ 0.13154796  0.67809954  0.47906236]
 [ 0.37534657  0.33351328  0.82201938]
 [ 0.77060722  0.53948973  0.30356941]
 [ 0.67318699  0.54926736  0.39101578]
 [ 0.63578907  0.36050915  0.67701791]
 [ 0.63804413  0.7194482   0.38707522]
 [ 0.08673964  0.8420653   0.29073816]]


In [12]:
#Find distance from 0.5
print("Distance from 0.5")
print(randarry-0.5)
print("Absolute distance from 0.5")
dist05=np.abs(randarry-0.5)
print(dist05)

Distance from 0.5
[[ 0.32203111  0.21669347  0.39493504]
 [ 0.48745974  0.41556332  0.13140939]
 [ 0.19521917 -0.41051919  0.19250661]
 [-0.36845204  0.17809954 -0.02093764]
 [-0.12465343 -0.16648672  0.32201938]
 [ 0.27060722  0.03948973 -0.19643059]
 [ 0.17318699  0.04926736 -0.10898422]
 [ 0.13578907 -0.13949085  0.17701791]
 [ 0.13804413  0.2194482  -0.11292478]
 [-0.41326036  0.3420653  -0.20926184]]
Absolute distance from 0.5
[[ 0.32203111  0.21669347  0.39493504]
 [ 0.48745974  0.41556332  0.13140939]
 [ 0.19521917  0.41051919  0.19250661]
 [ 0.36845204  0.17809954  0.02093764]
 [ 0.12465343  0.16648672  0.32201938]
 [ 0.27060722  0.03948973  0.19643059]
 [ 0.17318699  0.04926736  0.10898422]
 [ 0.13578907  0.13949085  0.17701791]
 [ 0.13804413  0.2194482   0.11292478]
 [ 0.41326036  0.3420653   0.20926184]]


In [14]:
print(np.argsort(dist05,axis=1))
indx_to_closest = np.argsort(dist05,axis=1)[:,0]
print(indx_to_closest)
print("Here I wanted the 0 column because the output from argsort is the")
print("INDEX to the element that should go into that location. That is, the")
print("value in location 0,0 is the index of the element from the 0th row")
print("that should go in the 0th column when sorted")

[[1 0 2]
 [2 1 0]
 [2 0 1]
 [2 1 0]
 [0 1 2]
 [1 2 0]
 [1 2 0]
 [0 1 2]
 [2 0 1]
 [2 1 0]]
[1 2 2 2 0 1 1 0 2 2]
Here I wanted the 0 column because the output from argsort is the
INDEX to the element that should go into that location. That is, the
value in location 0,0 is the index of the element from the 0th row
that should go in the 0th column when sorted


In [16]:
print(randarry)
print(randarry[np.arange(10),indx_to_closest])
print("Recall, we can actually index directly with argsort's output...but it's harder to read the code")
print(randarry[np.arange(10), np.argsort(dist05,axis=1)[:,0]])

[[ 0.82203111  0.71669347  0.89493504]
 [ 0.98745974  0.91556332  0.63140939]
 [ 0.69521917  0.08948081  0.69250661]
 [ 0.13154796  0.67809954  0.47906236]
 [ 0.37534657  0.33351328  0.82201938]
 [ 0.77060722  0.53948973  0.30356941]
 [ 0.67318699  0.54926736  0.39101578]
 [ 0.63578907  0.36050915  0.67701791]
 [ 0.63804413  0.7194482   0.38707522]
 [ 0.08673964  0.8420653   0.29073816]]
[ 0.71669347  0.63140939  0.69250661  0.47906236  0.37534657  0.53948973
  0.54926736  0.63578907  0.38707522  0.29073816]
Recall, we can actually index directly with argsort's output...but it's harder to read
[ 0.71669347  0.63140939  0.69250661  0.47906236  0.37534657  0.53948973
  0.54926736  0.63578907  0.38707522  0.29073816]


In [18]:
print("Recall this over-indexs into randarry")
print(randarry[:,indx_to_closest])

Recall this over-indexs into randarry
[[ 0.71669347  0.89493504  0.89493504  0.89493504  0.82203111  0.71669347
   0.71669347  0.82203111  0.89493504  0.89493504]
 [ 0.91556332  0.63140939  0.63140939  0.63140939  0.98745974  0.91556332
   0.91556332  0.98745974  0.63140939  0.63140939]
 [ 0.08948081  0.69250661  0.69250661  0.69250661  0.69521917  0.08948081
   0.08948081  0.69521917  0.69250661  0.69250661]
 [ 0.67809954  0.47906236  0.47906236  0.47906236  0.13154796  0.67809954
   0.67809954  0.13154796  0.47906236  0.47906236]
 [ 0.33351328  0.82201938  0.82201938  0.82201938  0.37534657  0.33351328
   0.33351328  0.37534657  0.82201938  0.82201938]
 [ 0.53948973  0.30356941  0.30356941  0.30356941  0.77060722  0.53948973
   0.53948973  0.77060722  0.30356941  0.30356941]
 [ 0.54926736  0.39101578  0.39101578  0.39101578  0.67318699  0.54926736
   0.54926736  0.67318699  0.39101578  0.39101578]
 [ 0.36050915  0.67701791  0.67701791  0.67701791  0.63578907  0.36050915
   0.36050915